### ISSUE TITLE
CSS calc()函数

### ISSUE THREAD

**Issue by spruceatmc** [spruceatmc/spruceblog#8]
# CSS calc()函数
> **spruce** 2022/07/11 _正愁每次要用js获取宽高_

使用calc()函数计算div宽度
```css
div {
    position: absolute;
    left: 50px;
    width: calc(100% - 100px);/*动态的100%，即使缩放页面也能改变*/
    background-color: yellow;
}
```
#### calc() 函数用于动态计算长度值
**运算符前后都需要保留一个空格**(我在这里卡了无数次),例如：width: calc(100% - 10px); 而不是width: calc(100%-10px);<br>
任何长度值都可以使用calc()函数进行计算;(em,vw,vh,px,%等)<br>
calc()函数支持 "+", "-", "*", "/" 运算;<br>
calc()函数使用标准的数学运算优先级规则<br>

## 注意的点
1.除数不能带单位
```css
div {
  /* 有效的*/
  margin: calc(30px / 3);
  /* 无效的*/
  margin: calc(30px / 10px);
  /* 无效的(不能除以0) */
  margin: calc(30px / 0);
}
```
2.加法(+)和减法(-)要求这两个数都是长度
```css
div {
  /* 有效的*/
  margin: calc(10px + 10px);
   /* 无效的*/
  margin: calc(10px + 5);
}
```
## 这就是个神技，会给代码带来许多方便，多学多用!
